### ISSUE TITLE
update help text for `assemble-spades --p-meta`

### ISSUE THREAD

**Issue by mikerobeson** [bokulich-lab/q2-assembly#55]
When running the command within the conda environment `qiime2-shotgun-2023.9`:

```
qiime assembly assemble-spades \
    --i-seqs fondue-output/single_reads.qza \
    --p-threads 8   \
    --p-phred-offset 33 \
    --p-memory 60 \
    --p-meta \
    --o-contigs contigs.qza  \
    --verbose
```

The following error was returned:

>Plugin error from assembly:
  SPAdes v3.15.2 in "meta" mode supports only paired-end reads.
See above for debug info.

Update the help text to reflect this.

**Comment by misialq** [comment]
Hey @mikerobeson, just to clarify: this error should appear only when you use the `--p-meta` flag, which is not included in the command you provided. Did you forget to add it there or did the error really occur with this exact set of inputs?

**Comment by mikerobeson** [comment]
Hi @misialq, sorry about that. Yes, the `--p-meta` flag was present. I was trying different options and copied the wrong set of commands. I've updated the command in the issue.
