### ISSUE TITLE
BUG: action `generate-reads` is missing the `pysam` dependency

### ISSUE THREAD

**Issue by misialq** [bokulich-lab/q2-assembly#60]
**Describe the bug**
When I try to run the `generate-reads` action, I get an error stating that the `pysam` module is missing.

**To Reproduce**
1. Create and activate the environment:
    ```
    mamba env create -n q2-shotgun --file https://data.qiime2.org/distro/shotgun/qiime2-shotgun-2023.9-py38-linux-conda.yml
    conda activate q2-shotgun
    qiime dev refresh-cache
    ```
1. Execute the command
    ```
    qiime assembly generate-reads \
        --i-genomes genomes.qza \
        --p-sample-names sample1 sample2 sample3 sample4 \
        --p-n-reads 2000000 \
        --p-abundance uniform \
        --p-n-genomes 5 \
        --p-cpus 10 \
        --output-dir reads \
        --verbose
    ```
    where genomes.qza is any FeatureData[Sequence] artifact. 
3. See error:
    ```
    Template genome sequences were provided - "n-genomes-ncbi" and "ncbi" parameters will be ignored.
    Running external command line application(s). This may print messages to stdout and/or stderr.
    The command(s) being run are below. These commands cannot be manually re-run as they will depend on temporary files that no longer exist.

    Command: iss generate --compress --genomes /scratch/mziemski/tmp/qiime2/mziemski/data/0619c364-72ba-492a-9d8f-7043e825bf15/data/dna-sequences.fasta --n_genomes 5 --abundance uniform --n_reads 2000000 --mode kde --model HiSeq --cpus 10 --output /scratch/mziemski/tmp/tmpowd79ql2/sample1_00_L001

    Traceback (most recent call last):
      File "/home/mziemski/miniconda3/envs/q2-shotgun-tutorial/bin/iss", line 6, in <module>
        from iss.app import main
      File "/home/mziemski/miniconda3/envs/q2-shotgun-tutorial/lib/python3.8/site-packages/iss/app.py", line 4, in <module>
        from iss import bam
      File "/home/mziemski/miniconda3/envs/q2-shotgun-tutorial/lib/python3.8/site-packages/iss/bam.py", line 14, in <module>
        import pysam
    ModuleNotFoundError: No module named 'pysam'
    ```

**Expected behavior**
The action runs without errors.

**Please complete the following information:**
 - OS: CentOS
 - QIIME 2 version: 2023.9

**Additional context**
This happened on both, Linux and macOS. I used the 2023.9 distro - for some reason the `pysam` package is not included there. Before, when I used to install q2-assembly "directly" from our conda channel, it seemed to work all fine. @lizgehret, @ebolyen would you have an idea why that could be happening? 🤔

**Comment by mikerobeson** [comment]
I received the same issue this morning. I also received this error:

>Plugin error from assembly:
  An error was encountered while running InSilicoSeq, (return code 1), please inspect stdout and stderr to learn more.
See above for debug info.

I assume the InSilicoSeq depends on pysam? I saw the pysam issue too.

**Comment by misialq** [comment]
Thanks for confirming @mikerobeson! Yes, it does depend on pysam but it also has it in the list of dependencies in its bioconda recipe so it should be included in the environment I guess... It used to be the case at least when I was installing it before, not using the distro route 😞

**Comment by ebolyen** [comment]
Looks like we need to add pysam to the recipe. I have no idea why the original tool isn't pulling that in, but I expect it's a particularly convoluted solve to get the rest of the distro working...
