### ISSUE TITLE
BUG: Download buttons for the `assembly evaluate-contigs` visualization not producing PDFs, etc..

### ISSUE THREAD

**Issue by mikerobeson** [bokulich-lab/q2-assembly#64]
The following command successfully runs and generates a QZV.

```
qiime assembly evaluate-contigs \
  --i-contigs megahit-contigs.qza \
  --p-min-contig 1000 \
  --p-threads 56 \
  --o-visualization megahit-contigs.qzv \
  --verbose
```

However, clicking on any of the "Downloads" buttons does not invoke a "download" of the respective PDFs & TSVs. Howewver, I can confirm that these files do exist within the extracted QZV under the `quast_data/` and `quast_data/basic_stats/` folder, using the command:

```
qiime tools extract \
--input-path megahit-contigs.qzv \
--output-path megahit-contigs-extract 
```

Tested within the Chrome and Safari browsers. Code ran within the `qiime2-shotgun-2023.9` environment.

**Comment by misialq** [comment]
Hey @mikerobeson, thanks for opening the issue! This should have been resolved by https://github.com/bokulich-lab/q2-assembly/pull/52. Does this look like what you were experiencing? Maybe you could try installing the most up-to-date version? Let me know, if it still doesn't work we may need to look into it again. Thanks!

**Comment by mikerobeson** [comment]
Oh gosh, I usually check through the open and closed issues to make sure I am not duplicating efforts. I am embarassed to have missed that one! I will make sure I have the latest version and try again.
